import fs from "node:fs";

const catalogPath = "data/decks/catalog.json";
const outputPath = "supabase-seed.sql";
const ALL_GENRES = "__all__";
const DEFAULT_GENRE = "未分類";

function sql(value) {
  if (value === null || value === undefined) return "null";
  return `'${String(value).replaceAll("'", "''")}'`;
}

function jsonb(value) {
  return `${sql(JSON.stringify(value))}::jsonb`;
}

function parseGenreHeading(line) {
  if (line.startsWith("#")) return line.replace(/^#+\s*/, "").trim();
  const bracketed = line.match(/^【(.+)】$/);
  return bracketed ? bracketed[1].trim() : "";
}

function parseLine(line, genre) {
  const delimiters = ["\t", " | ", "|", "=>", "::", "＝", "=", "：", ":"];
  const delimiter = delimiters.find((mark) => line.includes(mark));
  if (!delimiter) return null;

  const index = line.indexOf(delimiter);
  const question = line.slice(0, index).trim();
  const answerText = line.slice(index + delimiter.length).trim();
  const answers = answerText
    .split(/\s*(?:\/|／)\s*/)
    .map((answer) => answer.trim())
    .filter(Boolean);

  if (!question || !answers.length) return null;
  return { genre, question, answers };
}

function parseMarkdownDeck(path) {
  const text = fs.readFileSync(path, "utf8");
  const cards = [];
  let genre = DEFAULT_GENRE;

  text.split("\n").forEach((rawLine) => {
    const line = rawLine.trim();
    if (!line || line.startsWith("<!--")) return;
    const nextGenre = parseGenreHeading(line);
    if (nextGenre) {
      genre = nextGenre || DEFAULT_GENRE;
      return;
    }
    const card = parseLine(line, genre);
    if (card) cards.push(card);
  });

  return cards;
}

const decks = JSON.parse(fs.readFileSync(catalogPath, "utf8"));
const deckIds = decks.map((deck) => deck.id);
const lines = [
  "-- Generated by scripts/export_supabase_seed.mjs",
  "-- Run this in the Supabase SQL Editor. It upserts deck metadata and replaces cards for these decks.",
  "begin;",
  "",
];

lines.push("insert into public.quiz_decks (id, title, badge, description, status, source_type, sort_order) values");
lines.push(
  decks
    .map((deck, index) => `  (${[
      sql(deck.id),
      sql(deck.title),
      sql(deck.badge || ""),
      sql(deck.description || ""),
      sql(deck.status || "pending"),
      sql("supabase"),
      index,
    ].join(", ")})`)
    .join(",\n") +
    "\non conflict (id) do update set\n  title = excluded.title,\n  badge = excluded.badge,\n  description = excluded.description,\n  status = excluded.status,\n  source_type = excluded.source_type,\n  sort_order = excluded.sort_order;",
);

lines.push("");
lines.push(`delete from public.quiz_cards where deck_id in (${deckIds.map(sql).join(", ")});`);
lines.push("");

const cardRows = [];
decks.forEach((deck) => {
  if (deck.status !== "ready" || !deck.deckPath) return;
  const deckPath = deck.deckPath.replace(/^\.\//, "");
  if (!fs.existsSync(deckPath)) return;
  const cards = parseMarkdownDeck(deckPath).filter((card) => card.genre !== ALL_GENRES);
  cards.forEach((card, index) => {
    cardRows.push(`  (${[
      sql(deck.id),
      sql(card.genre || DEFAULT_GENRE),
      sql(card.question),
      jsonb(card.answers),
      index,
    ].join(", ")})`);
  });
});

if (cardRows.length) {
  lines.push("insert into public.quiz_cards (deck_id, genre, question, answers, sort_order) values");
  lines.push(`${cardRows.join(",\n")};`);
  lines.push("");
}

lines.push("commit;");
lines.push("");

fs.writeFileSync(outputPath, lines.join("\n"));
console.log(JSON.stringify({ decks: decks.length, readyDecks: decks.filter((deck) => deck.status === "ready").length, cards: cardRows.length, outputPath }, null, 2));
